---
general:
  model_type: single #Pick from: single, double, multi
  save_results: yes
  render_training: no
  render_evaluation: no
  verbose: yes
uncertainty:
  wind:
    enabled: yes
    default: 0
    range: [1, 19]
    value: None
  gravity:
    enabled: yes
    default: -10
    range: [ -15, -5 ]
    value: None
  random_start_position:
    enabled: yes
    default: [ 300, 400 ]
    x_range: [ 0, 550 ]
    y_range: [ 400, 401 ]
    value: None
network:
  layers:
    - nodes: 64
      activation: relu
    - nodes: 64
      activation: relu
    - nodes: 4
      activation: linear
  loss_function: mse
  optimizer: adam
  learning_rate: 0.001
training:
  batch_size: 64
  epsilon:
    min: 0.01
    max: 0.2
    change: 1
number_of_episodes: 350
max_steps: 1000
number_of_actions: 4
gamma: 0.99
save_location: ../saved_models/
memory:
  size: 1000000
evaluation_episodes: 1
best_score: 100
robust_test_threshold: 100
